# Test case of a data of bank customers leaving the bank. This ANN will predict the probability of a customer either about to leave or not

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print('X shape', X.shape)
print(X)
print('y shape', y.shape)
print(y)

X shape (10000, 10)
[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y shape (10000,)
[1 0 1 ... 1 1 0]


# Encoding categorical data

In [3]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
# label encoder column 1
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
# label encoder column 2
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]
X


/home/agha/anaconda3/lib/python3.5/site-packages/sklearn/preprocessing/_encoders.py:363: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/agha/anaconda3/lib/python3.5/site-packages/sklearn/preprocessing/_encoders.py:385: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

## Splitting the dataset into the Training set and Test set

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


In [5]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


# ANN

In [6]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 20, epochs = 100)


Using TensorFlow backend.


Epoch 1/100
8000/8000 [==============================] - 1s 121us/step - loss: 0.5401 - acc: 0.7946
Epoch 2/100
8000/8000 [==============================] - 1s 80us/step - loss: 0.4333 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 73us/step - loss: 0.4288 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 76us/step - loss: 0.4266 - acc: 0.7960
Epoch 5/100
8000/8000 [==============================] - 1s 76us/step - loss: 0.4241 - acc: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 74us/step - loss: 0.4214 - acc: 0.7970
Epoch 7/100
8000/8000 [==============================] - 1s 74us/step - loss: 0.4189 - acc: 0.8195
Epoch 8/100
8000/8000 [==============================] - 1s 74us/step - loss: 0.4170 - acc: 0.8241
Epoch 9/100
8000/8000 [==============================] - 1s 76us/step - loss: 0.4153 - acc: 0.8275
Epoch 10/100
8000/8000 [==============================] - 1s 74us/step - loss: 0.4139 - acc: 0.8294
Epoch 11

8000/8000 [==============================] - 1s 77us/step - loss: 0.3984 - acc: 0.8355
Epoch 84/100
8000/8000 [==============================] - 1s 76us/step - loss: 0.3984 - acc: 0.8356
Epoch 85/100
8000/8000 [==============================] - 1s 81us/step - loss: 0.3982 - acc: 0.8363
Epoch 86/100
8000/8000 [==============================] - 1s 72us/step - loss: 0.3984 - acc: 0.8370
Epoch 87/100
8000/8000 [==============================] - 1s 76us/step - loss: 0.3983 - acc: 0.8358
Epoch 88/100
8000/8000 [==============================] - 1s 76us/step - loss: 0.3984 - acc: 0.8359
Epoch 89/100
8000/8000 [==============================] - 1s 75us/step - loss: 0.3984 - acc: 0.8348
Epoch 90/100
8000/8000 [==============================] - 1s 74us/step - loss: 0.3980 - acc: 0.8346
Epoch 91/100
8000/8000 [==============================] - 1s 75us/step - loss: 0.3984 - acc: 0.8363
Epoch 92/100
8000/8000 [==============================] - 1s 75us/step - loss: 0.3982 - acc: 0.8380
Epoch 93/100


# Part 3 - Making predictions and evaluating the model

In [7]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
# Threshold
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1541,   54],
       [ 256,  149]])

In [8]:
# calculate above result
print((1541+149)/2000)

0.845


In [9]:
# Predicting a single new observation
"""Predict if the customer with the following informations will leave the bank:
Geography: France
Credit Score: 600
Gender: Male
Age: 40
Tenure: 3
Balance: 60000
Number of Products: 2
Has Credit Card: Yes
Is Active Member: Yes
Estimated Salary: 50000"""

new_prediction = classifier.predict(sc.transform(np.array([[0.0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))
new_prediction = (new_prediction > 0.5)
print(new_prediction)


[[False]]
